#!/bin/bash

DELAY=3 # Number of seconds to display results

while [[ "$REPLY" != 0 ]]; do
	clear
	cat <<- _EOF_
		Please select:
		
		1. Display System Information
		2. Display Disk Space
		3. Display Home Space Utilization
		0. Quit
		
	_EOF_
	read -p "Enter the selection [0-3] > "
	
	# regular expressions are used in the match body, ie 1) the character 1, A|a) either a character or A character, *) anything
	case "$REPLY" in
		1)	echo "Hostname: $HOSTNAME"
			uptime
			;;
		2)	df -h
			;;
		3)	if [[ $(id -u) -eq 0 ]]; then
				echo "Home Space Utilization (All users)"
				du -sh /home/*
			else
				echo "Home Space utilization ($USER)"
				du -sh "$HOME"
			fi
			;;
		0)	echo "Program terminated"
			;;
		*)	echo "Invalid entry." >&2
			;;
	esac
	sleep "$DELAY"
done
